name: Deploy

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    outputs:
      public_ip: ${{ steps.get-ip.outputs.public_ip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.6
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: Bridge-Sensor-Dashboard

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Bridge-Sensor-Dashboard

      - name: Get EC2 IP
        id: get-ip
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> "$GITHUB_OUTPUT"
        working-directory: Bridge-Sensor-Dashboard

  build-and-deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: Bridge-Sensor-Dashboard
          push: true
          tags: bigkola1/bridge-sensor-dashboard:latest

      - name: Set up Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Run Ansible playbook
        env:
          EC2_IP: ${{ needs.terraform.outputs.public_ip }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh-key.pem
          chmod 600 ssh-key.pem

          echo "Waiting for cloud-init to finish..."
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@"$EC2_IP" "sudo cloud-init status --wait"

          cat > inventory.yml << EOF
          webservers:
            hosts:
              bridge-server:
                ansible_host: $EC2_IP
                ansible_user: ubuntu
                ansible_ssh_private_key_file: ssh-key.pem
          EOF

          ansible-playbook -i inventory.yml Bridge-Sensor-Dashboard/playbook.yml
