name: Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: bigkola1/bridge-sensor-dashboard:latest
          context: Bridge-Sensor-Dashboard

      - name: SSH into EC2 and update container
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh-key.pem
          chmod 600 ssh-key.pem
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@${{ secrets.EC2_EIP }} '
          sudo docker pull bigkola1/bridge-sensor-dashboard:latest
          sudo docker stop bridge-sensor
          sudo docker rm bridge-sensor
          sudo docker run -d -p 80:80 --name bridge-sensor bigkola1/bridge-sensor-dashboard:latest'